services:

  redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    command: --port ${REDIS_PORT}
    volumes:
      - ./app_data/redis:/data
    networks:
      - proxy_net

  bot:
    container_name: ${BOT_NAME}
    build:
      dockerfile: ./Dockerfile
    image: mycego_bot
    restart: on-failure
    volumes:
      - ./app_data:/bot/app_data
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    networks:
      - proxy_net

networks:
  proxy_net:
    name: proxy_net
