services:

#  postgres:
#    container_name: postgres
#    image: postgres:latest
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    command:
#      - "postgres"
#      - "-c"
#      - "log_destination=stderr"
#      - "-c"
#      - "logging_collector=on"
#      - "-c"
#      - "log_directory=/tmp/logs"
#    volumes:
#      - ./app_data/database:/var/lib/postgresql/data
#      - ./app_data/logs/postgres:/var/postgres/logs
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: pg_isready -U admin
#      interval: 10s
#      timeout: 10s
#      retries: 3
#
#  redis:
#    container_name: redis
#    image: redis:latest
#
#    healthcheck:
#      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
#      interval: 10s
#      timeout: 10s
#      retries: 3
#
#    ports:
#      - "6379:6379"
#
#
  bot:
    container_name: bot
    build:
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - ./app_data:/bot/app_data
    env_file:
      - .env
