services:

#
#  db:
#    image:
  redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    command: --port ${REDIS_PORT}
    volumes:
      - ./app_data/redis:/data
    networks:
      - proxy_net

  bot:
    container_name: ${BOT_NAME}
    build:
      dockerfile: ./Dockerfile
    image: mycego_bot
    restart: on-failure
    volumes:
      - ./app_data:/bot/app_data
      - ./logs/bot:/bot/logs
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    networks:
      - proxy_net

  celery:
    build:
      dockerfile: ./Dockerfile
    container_name: ${CELERY_CONTAINER}
    entrypoint: celery -A celery_main.bot_celery worker --autoscale=2,1 --loglevel=info
    env_file:
      - .env
    volumes:
      - ./logs/celery:/bot/logs
      - ./app_data:/bot/app_data
    depends_on:
      - redis
    networks:
      - proxy_net

  celery-beat:
    build:
      dockerfile: ./Dockerfile
    container_name: ${CELERY_BEAT_CONTAINER}
    entrypoint: celery -A celery_main.bot_celery beat --loglevel=info
    env_file:
      - .env
    volumes:
      - ./logs/celery_beat:/bot/logs
      - ./app_data:/bot/app_data
    depends_on:
      - redis
    networks:
      - proxy_net

networks:
  proxy_net:
    name: proxy_net
