"""initial

Revision ID: 3641d8d4fdfd
Revises: 
Create Date: 2024-07-25 14:21:13.168406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3641d8d4fdfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('users',
                        sa.Column('telegram_id', sa.String(), nullable=False),
                        sa.Column('site_user_id', sa.String(), nullable=True),
                        sa.Column('username', sa.String(), nullable=True),
                        sa.Column('username_tg', sa.String(), nullable=True),
                        sa.Column('first_name', sa.String(), nullable=True),
                        sa.Column('last_name', sa.String(), nullable=True),
                        sa.Column('role', sa.String(), nullable=True),
                        sa.PrimaryKeyConstraint('telegram_id'),
                        sa.UniqueConstraint('site_user_id'),
                        sa.UniqueConstraint('username')
                        )
    except sa.exc.OperationalError:
        pass
    try:
        op.create_table('works',
                        sa.Column('id', sa.String(), nullable=False),
                        sa.Column('name', sa.String(), nullable=True),
                        sa.Column('delivery', sa.Boolean(), nullable=True),
                        sa.Column('standard', sa.Integer(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
    except sa.exc.OperationalError:
        pass
    try:
        op.create_table('messages',
                        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                        sa.Column('user_id', sa.String(), nullable=True),
                        sa.Column('text', sa.String(), nullable=True),
                        sa.Column('timestamp', sa.DateTime(), nullable=True),
                        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
                        sa.PrimaryKeyConstraint('id')
                        )
    except sa.exc.OperationalError:
        pass
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('messages')
    # op.drop_table('works')
    # op.drop_table('users')
    pass
    # ### end Alembic commands ###
