"""empty message

Revision ID: c01756b91f8b
Revises: 491b0c2450e5
Create Date: 2024-10-08 13:21:25.232507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b155705b43'
down_revision: Union[str, None] = '491b0c2450e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("works")
    op.create_table(
        "works",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("delivery", sa.Integer(), nullable=False),
        sa.Column("standard", sa.Integer(), nullable=False),
        sa.Column("department_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("works_id", "works", ["id"])
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.String(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
