"""empty message

Revision ID: 6c29e2c491b8
Revises: 47b155705b43
Create Date: 2024-11-01 13:51:38.843671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c29e2c491b8"
down_revision: Union[str, None] = "47b155705b43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "date_joined",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("date_joined")

    # ### end Alembic commands ###
