"""init

Revision ID: addfbb7b2797
Revises: 
Create Date: 2024-07-30 14:27:52.353236

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "addfbb7b2797"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("user_site_user_id")
        batch_op.drop_index("user_telegram_id")
        batch_op.drop_index("user_username")
        batch_op.create_unique_constraint("telegram_id", ["telegram_id"])
        batch_op.create_unique_constraint("site_user_id", ["site_user_id"])
        batch_op.create_unique_constraint("username", ["username"])

    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.add_column(sa.Column("department_name", sa.String(), nullable=True))
        batch_op.drop_index("works_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.create_index("works_id", ["id"], unique=1)
        batch_op.drop_column("department_name")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("telegram_id", type_="unique")
        batch_op.drop_constraint("site_user_id", type_="unique")
        batch_op.drop_constraint("username", type_="unique")
        batch_op.create_index("user_username", ["username"], unique=1)
        batch_op.create_index("user_telegram_id", ["telegram_id"], unique=1)
        batch_op.create_index("user_site_user_id", ["site_user_id"], unique=1)

    # ### end Alembic commands ###
