"""works added department name

Revision ID: cda2c7ee7939
Revises: 3641d8d4fdfd
Create Date: 2024-07-25 14:24:50.343890

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cda2c7ee7939"
down_revision: Union[str, None] = "3641d8d4fdfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("works", sa.Column("department_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("works", "department_name")
    # ### end Alembic commands ###
